# Generated by Django 4.1.1 on 2022-09-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_3',
            field=models.BooleanField(default=False),
        ),
    ]
