# Generated by Django 4.1.1 on 2022-09-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_subject_2_student_subject_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subject_1',
            new_name='CG',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject_2',
            new_name='FDS',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject_3',
            new_name='OOP',
        ),
    ]
